name: snapshare
description: "A simplified photo-sharing app for connecting with friends"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

 #---------------PACKAGES---------------#
dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.6.0

  # State Management
  get: ^4.6.6

  # Utility Packages
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.0.4

  # Product Specific Packages


  #---------------./ PACKAGES END---------------#


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  #---------------LOCAL ASSETS---------------#
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  #---------------LOCAL FONTS---------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

  
  
